apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-spring-boot-deployment
  labels:
    app: hello-spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-spring-boot
  template:
    metadata:
      labels:
        app: hello-spring-boot
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: hello-spring-boot
          image: gsahudockerhub/hello-spring-boot:latest  # Replace 'yourusername' with your Docker Hub username
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
